### sign in
POST http://localhost:3000/auth/signIn
Content-Type: application/json

{
  "username": "ning",
  "password": "ning"
}


### register
POST http://localhost:3000/auth/signUp
Content-Type: application/json

{
  "username": "ning",
  "password": "ning"
}


### get photos
GET http://localhost:3000/photo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5pbmciLCJzdWIiOjEsImlhdCI6MTY4ODM1NDA2NCwiZXhwIjoxNjg4MzU3NjY0fQ.BhwbimxXrWQRsuXcCCHAKdEooi-gfD38Rk6w8WtKdec

